<?php

return [
    'modules' => [

        'home_visitation' => [
            'title' => 'Home Visitation',
            'model' => App\Models\HomeVisitation::class,
            'fields' => [
                'jina' => 'Jina la Mshiriki',
                'namba' => 'Namba ya Mshiriki',
                'shule' => 'Shule',
                'darasa' => 'Darasa',
                'last_program' => 'Last Program',
                'likes_program' => 'Anapenda Program',
                'participant_comments' => 'Maoni ya Mshiriki',
                'mtaa' => 'Mtaa',
                'mazingira' => 'Mazingira',
                'nyumba' => 'Nyumba',
                'paa' => 'Paa',
                'choo' => 'Choo',
                'milo' => 'Milo kwa Siku',
                'wanaume' => 'Wanaume',
                'wanawake' => 'Wanawake',
                'tabia' => 'Tabia',
                'visit_date' => 'Tarehe ya Ziara',
                'maoni' => 'Maoni',
                'mtembelezaji' => 'Mtembelezaji',
                'nafasi' => 'Nafasi',
                'created_at' => 'Created At',
            ],
        ],

        'school_visitation' => [
            'title' => 'School Visitation',
            'model' => App\Models\SchoolVisitation::class,
            'fields' => [
                'participant_name' => 'Jina la Mshiriki',
                'registration_number' => 'Namba ya Usajili',
                'school_name' => 'Jina la Shule',
                'class_level' => 'Darasa',
                'participant_presence' => 'Mshiriki Yupo au Hayupo',
                'academic_progress' => 'Maendeleo ya Kitaaluma',
                'academic_challenges' => 'Changamoto za Kitaaluma',
                'discipline_status' => 'Nidhamu',
                'bad_behaviors' => 'Tabia Mbaya',
                'cleanliness_status' => 'Hali ya Usafi',
                'teacher_comments' => 'Maoni ya Mwalimu',
                'visitor_comments' => 'Maoni ya Mtembeleaji',
                'created_at' => 'Created At',
            ],
        ],

        'local_sponsorship' => [
            'title' => 'Local Sponsorship',
            'model' => App\Models\LocalSponsorship::class,
            'fields' => [
                'child_name' => 'Child Name',
                'child_age' => 'Child Age',
                'child_location' => 'Child Location',
                'sponsor_type' => 'Sponsor Type',
                'sponsor_name' => 'Sponsor Name',
                'local_number' => 'Child Local Number',
                'created_at' => 'Created At',
            ],
        ],

        'school_primary' => [
            'title' => 'Primary School Information',
            'model' => App\Models\SchoolInformationRecord::class,
            'where' => ['education_level' => 'primary'],
            'fields' => [
                'student_name' => 'Jina la Mtoto',
                'school_name' => 'Jina la Shule',
                'class_level' => 'Darasa',
                'graduation_year' => 'Mwaka wa Kuhitimu',
                'performance' => 'Ufaulu',
                'best_subjects' => 'Masomo Anayofanya Vizuri',
                'failed_subjects' => 'Masomo Anayofeli',
                'child_dream' => 'Ndoto ya Mtoto',
                'general_comments' => 'Maoni',
            ],
        ],

        'school_secondary' => [
            'title' => 'Secondary School Information',
            'model' => App\Models\SchoolInformationRecord::class,
            'where' => ['education_level' => 'secondary'],
            'fields' => [
                'student_name' => 'Jina la Mtoto',
                'school_name' => 'Jina la Shule',
                'class_level' => 'Darasa',
                'graduation_year' => 'Mwaka wa Kuhitimu',
                'performance' => 'Ufaulu',
                'best_subjects' => 'Masomo Anayofanya Vizuri',
                'failed_subjects' => 'Masomo Anayofeli',
                'child_dream' => 'Ndoto ya Mtoto',
                'general_comments' => 'Maoni',
            ],
        ],

        'school_a_level' => [
            'title' => 'A-Level School Information',
            'model' => App\Models\SchoolInformationRecord::class,
            'where' => ['education_level' => 'a-level'],
            'fields' => [
                'student_name' => 'Jina la Mwanafunzi',
                'school_name' => 'Jina la Shule',
                'class_level' => 'Level / Combination',
                'graduation_year' => 'Mwaka wa Kuhitimu',
                'performance' => 'Ufaulu',
                'best_subjects' => 'Masomo Mazuri',
                'failed_subjects' => 'Masomo Yenye Changamoto',
                'child_dream' => 'Ndoto ya Mtoto',
                'general_comments' => 'Maoni',
            ],
        ],

        'school_college' => [
            'title' => 'College Information',
            'model' => App\Models\SchoolInformationRecord::class,
            'where' => ['education_level' => 'college'],
            'fields' => [
                'student_name' => 'Jina la Mwanafunzi',
                'college_name' => 'Jina la Chuo',
                'course_program' => 'Kozi / Programu',
                'program_level' => 'Kiwango',
                'completion_date' => 'Tarehe ya Kukamilisha',
                'college_address' => 'Anwani ya Chuo',
                'current_challenges' => 'Changamoto za Sasa',
            ],
        ],

        'school_university' => [
            'title' => 'University Information',
            'model' => App\Models\SchoolInformationRecord::class,
            'where' => ['education_level' => 'university'],
            'fields' => [
                'student_name' => 'Jina la Mwanafunzi',
                'university_name' => 'Jina la Chuo Kikuu',
                'course_program' => 'Kozi / Programu',
                'level_of_study' => 'Kiwango',
                'completion_date' => 'Tarehe ya Kukamilisha',
                'university_address' => 'Anwani ya Chuo Kikuu',
                'current_challenges' => 'Changamoto za Sasa',
            ],
        ],

        'school_vocational_training' => [
            'title' => 'Vocational Training Information',
            'model' => App\Models\SchoolInformationRecord::class,
            'where' => ['education_level' => 'vocational-training'],
            'fields' => [
                'student_name' => 'Jina la Mwanafunzi',
                'institution_name' => 'Jina la Taasisi',
                'course_program' => 'Kozi / Programu',
                'training_duration' => 'Muda wa Mafunzo',
                'completion_date' => 'Tarehe ya Kukamilisha',
                'current_challenges' => 'Changamoto',
            ],
        ],

        'school_others' => [
            'title' => 'Other Education Information',
            'model' => App\Models\SchoolInformationRecord::class,
            'where' => ['education_level' => 'others'],
            'fields' => [
                'student_name' => 'Jina la Mwanafunzi',
                'institution_name' => 'Jina la Taasisi',
                'program_name' => 'Programu',
                'study_level' => 'Kiwango',
                'completion_date' => 'Tarehe ya Kukamilisha',
                'current_challenges' => 'Changamoto',
            ],
        ],

        'exam_primary' => [
            'title' => 'Primary Exam Results',
            'model' => App\Models\ExamResult::class,
            'where' => ['education_level' => 'primary'],
            'fields' => [
                'student_name' => 'Jina la Mwanafunzi',
                'school_name' => 'Shule / Taasisi',
                'class_level' => 'Darasa / Ngazi',
                'exam_type' => 'Aina ya Mtihani',
                'exam_year' => 'Mwaka wa Mtihani',
                'performance' => 'Ufaulu wa Jumla',
                'best_subjects' => 'Masomo Aliyofanya Vizuri',
                'failed_subjects' => 'Masomo Yenye Changamoto',
                'comments' => 'Maoni',
                'created_at' => 'Created At',
            ],
        ],

        'exam_secondary' => [
            'title' => 'Secondary Exam Results',
            'model' => App\Models\ExamResult::class,
            'where' => ['education_level' => 'secondary'],
            'fields' => [
                'student_name' => 'Jina la Mwanafunzi',
                'school_name' => 'Shule / Taasisi',
                'class_level' => 'Darasa / Ngazi',
                'exam_type' => 'Aina ya Mtihani',
                'exam_year' => 'Mwaka wa Mtihani',
                'performance' => 'Ufaulu wa Jumla',
                'best_subjects' => 'Masomo Aliyofanya Vizuri',
                'failed_subjects' => 'Masomo Yenye Changamoto',
                'comments' => 'Maoni',
                'created_at' => 'Created At',
            ],
        ],

        'exam_a_level' => [
            'title' => 'A-Level Exam Results',
            'model' => App\Models\ExamResult::class,
            'where' => ['education_level' => 'a-level'],
            'fields' => [
                'student_name' => 'Jina la Mwanafunzi',
                'school_name' => 'Shule / Taasisi',
                'class_level' => 'Darasa / Ngazi',
                'exam_type' => 'Aina ya Mtihani',
                'exam_year' => 'Mwaka wa Mtihani',
                'performance' => 'Ufaulu wa Jumla',
                'best_subjects' => 'Masomo Aliyofanya Vizuri',
                'failed_subjects' => 'Masomo Yenye Changamoto',
                'comments' => 'Maoni',
                'created_at' => 'Created At',
            ],
        ],

        'exam_college' => [
            'title' => 'College Exam Results',
            'model' => App\Models\ExamResult::class,
            'where' => ['education_level' => 'college'],
            'fields' => [
                'student_name' => 'Jina la Mwanafunzi',
                'school_name' => 'Shule / Taasisi',
                'class_level' => 'Darasa / Ngazi',
                'exam_type' => 'Aina ya Mtihani',
                'exam_year' => 'Mwaka wa Mtihani',
                'gpa' => 'GPA',
                'best_subjects' => 'Masomo Aliyofanya Vizuri',
                'failed_subjects' => 'Masomo Yenye Changamoto',
                'comments' => 'Maoni',
                'created_at' => 'Created At',
            ],
        ],

        'exam_university' => [
            'title' => 'University Exam Results',
            'model' => App\Models\ExamResult::class,
            'where' => ['education_level' => 'university'],
            'fields' => [
                'student_name' => 'Jina la Mwanafunzi',
                'school_name' => 'Shule / Taasisi',
                'class_level' => 'Darasa / Ngazi',
                'exam_type' => 'Aina ya Mtihani',
                'exam_year' => 'Mwaka wa Mtihani',
                'gpa' => 'GPA',
                'best_subjects' => 'Masomo Aliyofanya Vizuri',
                'failed_subjects' => 'Masomo Yenye Changamoto',
                'comments' => 'Maoni',
                'created_at' => 'Created At',
            ],
        ],

        'talent_attendance' => [
            'title' => 'Talent Attendance',
            'model' => App\Models\TalentAttendance::class,
            'fields' => [
                'date' => 'Date',
                'instructor_name' => 'Instructor Name',
                'talent_taught' => 'Talent Taught',
                'attendance_count' => 'Attendance Count',
                'instructor_comments' => 'Instructor Comments',
                'supervisor_comments' => 'Supervisor Comments',
                'lesson_topic' => 'Lesson Topic',
                'created_at' => 'Created At',
            ],
        ],

        'skills_attendance' => [
            'title' => 'Skills Attendance',
            'model' => App\Models\SkillsAttendance::class,
            'fields' => [
                'date' => 'Date',
                'teacher_name' => 'Teacher Name',
                'lesson_topic' => 'Lesson Topic',
                'present_count' => 'Present Count',
                'teacher_comments' => 'Teacher Comments',
                'supervisor_comments' => 'Supervisor Comments',
                'lesson_topic_details' => 'Lesson Topic Details',
                'created_at' => 'Created At',
            ],
        ],

        'curriculum_attendance' => [
            'title' => 'Curriculum Attendance',
            'model' => App\Models\CurriculumAttendance::class,
            'fields' => [
                'tarehe' => 'Tarehe',
                'jina_la_mwalimu' => 'Jina la Mwalimu',
                'somo' => 'Somo',
                'wahudhuria' => 'Waliohudhuria',
                'maoni_ya_mwalimu' => 'Maoni ya Mwalimu',
                'maoni_ya_msimamizi' => 'Maoni ya Msimamizi',
                'mada' => 'Mada',
                'created_at' => 'Created At',
            ],
        ],

        'masomo_ya_mtaala' => [
            'title' => 'Masomo ya Mtaala',
            'model' => App\Models\MasomoYaMtaala::class,
            'fields' => [
                'tarehe' => 'Tarehe',
                'jina_la_mwalimu' => 'Jina la Mwalimu',
                'somo_analofundisha' => 'Somo Analofundisha',
                'kiroho' => 'Kiroho',
                'kimwili' => 'Kimwili',
                'kiakili' => 'Kiakili',
                'kijamii' => 'Kijamii',
                'darasa_la_mjaka_mingapi' => 'Darasa',
                'mada_aliyo_fundisha' => 'Mada',
                'maoni_ya_mwanafunzi' => 'Maoni ya Mwanafunzi',
                'maoni_ya_mwalimu' => 'Maoni ya Mwalimu',
                'submitted_at' => 'Submitted At',
                'created_at' => 'Created At',
            ],
        ],

        'masomo_ya_fani' => [
            'title' => 'Masomo ya Fani',
            'model' => App\Models\MasomoYaFani::class,
            'fields' => [
                'date' => 'Tarehe',
                'teacher' => 'Jina la Mwalimu',
                'fani_type' => 'Aina ya Fani',
                'topic' => 'Mada',
                'student_preferences' => 'Washiriki Wanapendelea Nini',
                'student_feedback' => 'Maoni ya Mwanafunzi',
                'teacher_feedback' => 'Maoni ya Mwalimu',
                'submitted_at' => 'Submitted At',
                'created_at' => 'Created At',
            ],
        ],

        'special_program' => [
            'title' => 'Special Program',
            'model' => App\Models\SpecialProgram::class,
            'fields' => [
                'date' => 'Tarehe',
                'teacher' => 'Mwalimu',
                'topic' => 'Mada',
                'student_feedback' => 'Maoni ya Mwanafunzi',
                'teacher_feedback' => 'Maoni ya Mwalimu',
                'status' => 'Status',
                'submitted_at' => 'Submitted At',
                'created_at' => 'Created At',
            ],
        ],

        'skills_information' => [
            'title' => 'Skills Information',
            'model' => App\Models\SkillsInformation::class,
            'fields' => [
                'student_name' => 'Student Name',
                'gender' => 'Gender',
                'student_id' => 'Student ID',
                'skill_category' => 'Skill Category',
                'specific_skills' => 'Specific Skills',
                'skills_type' => 'Skills Type',
                'group_skills_details' => 'Group Skills Details',
                'skill_level' => 'Skill Level',
                'has_certification' => 'Has Certification',
                'certification_details' => 'Certification Details',
                'mentor' => 'Mentor',
                'challenges' => 'Challenges',
                'support_received' => 'Support Received',
                'comments' => 'Comments',
                'created_at' => 'Created At',
            ],
        ],

        'parents_information' => [
            'title' => 'Parents Information',
            'model' => App\Models\ParentsInformation::class,
            'fields' => [
                'parent_name' => 'Parent Name',
                'parent_of' => 'Parent Of',
                'activity' => 'Activity',
                'support_type' => 'Support Type',
                'address' => 'Address',
                'parent_comments' => 'Parent Comments',
                'supervisor_comments' => 'Supervisor Comments',
                'submission_date' => 'Submission Date',
                'status' => 'Status',
                'admin_comments' => 'Admin Comments',
                'approved_at' => 'Approved At',
                'created_at' => 'Created At',
            ],
        ],

        'vocational_training' => [
            'title' => 'Vocational Training',
            'model' => App\Models\VocationalTraining::class,
            'fields' => [
                'student_name' => 'Student Name',
                'school_name' => 'School / Institution',
                'skill_category' => 'Skill Category',
                'training_level' => 'Training Level',
                'created_at' => 'Created At',
            ],
        ],

        'saving_groups' => [
            'title' => 'Savings Groups',
            'model' => App\Models\SavingGroup::class,
            'fields' => [
                'group_name' => 'Group Name',
                'member_count' => 'Members',
                'group_mentor' => 'Group Mentor',
                'registration_status' => 'Registration Status',
                'savings_level' => 'Savings Level',
                'bank_account' => 'Bank Account',
                'group_progress' => 'Group Progress',
                'created_at' => 'Created At',
            ],
        ],

        'base_leader' => [
            'title' => 'Base Leader',
            'model' => App\Models\BaseLeader::class,
            'fields' => [
                'base_name' => 'Base Name',
                'leaders_count' => 'Leaders Count',
                'meeting_count' => 'Meeting Count',
                'term_end' => 'Term End',
                'additional_notes' => 'Additional Notes',
                'approval_status' => 'Approval Status',
                'admin_comments' => 'Admin Comments',
                'approved_at' => 'Approved At',
                'created_at' => 'Created At',
            ],
        ],

        'center_leader' => [
            'title' => 'Center Leader',
            'model' => App\Models\CenterLeadership::class,
            'fields' => [
                'center_name' => 'Center Name',
                'leadership_list' => 'Leadership List',
                'challenges' => 'Challenges',
                'feedback' => 'Feedback',
                'status' => 'Status',
                'created_at' => 'Created At',
            ],
        ],

        'cluster_leader' => [
            'title' => 'Cluster Leader',
            'model' => App\Models\ClusterLeader::class,
            'fields' => [
                'cluster_name' => 'Cluster Name',
                'yds_name' => 'YDS Name',
                'leaders_count' => 'Leaders Count',
                'meeting_count' => 'Meeting Count',
                'gethro_practice' => 'Gethro Practice',
                'term_end' => 'Term End',
                'additional_notes' => 'Additional Notes',
                'created_at' => 'Created At',
            ],
        ],

        'national_leader' => [
            'title' => 'National Leader',
            'model' => App\Models\NationalLeader::class,
            'fields' => [
                'center' => 'Center',
                'term_end' => 'Term End',
                'challenges' => 'Challenges',
                'comments' => 'Comments',
                'created_at' => 'Created At',
            ],
        ],

        'out_of_ministry' => [
            'title' => 'Out of Ministry',
            'model' => App\Models\OutOfMinistryLeader::class,
            'fields' => [
                'leaders_count' => 'Leaders Count',
                'term_end' => 'Term End',
                'created_at' => 'Created At',
            ],
        ],
        
        'talents_information' => [
    'title' => 'Talents Information',
    'model' => App\Models\TalentsInformation::class,
    'fields' => [
        'student_name' => 'Student Name',
        'participant_number' => 'Participant Number',
        'age' => 'Age',
        'gender' => 'Gender',
        'mentor' => 'Mentor',
        'talent_type' => 'Talent Type',
        'talent_description' => 'Talent Description',
        'talent_duration' => 'Talent Duration',
        'has_competed' => 'Has Competed',
        'competition_details' => 'Competition Details',
        'achievements' => 'Achievements',
        'needs_training' => 'Needs Training',
        'training_details' => 'Training Details',
        'comments' => 'Comments',
        'created_at' => 'Created At',
    ],
],
    ],
];
